name = "guardian-text-cloudflare-worker"
type = "javascript"
account_id = "${env:CF_ACCOUNT_ID}"
workers_dev = false

[build]
command = "npm install && npm run build"
output = "dist"

[site]
bucket = "./dist"
entry-point = "worker"

